[package]
name = "vectordb"
version = "0.1.0"
edition = "2024"

[dependencies]
tiktoken-rs = "0.7.0"
fastembed = "5.2.0"
bincode = "2.0.1"
axum = "0.8.6"
tokio = { version = "1.28.2", features = ["rt-multi-thread"] }
serde = "1.0.228"
